export const sentences = [
  "The cow jumped over the moon",
  "The chicken crossed the road",
  "The cat got your tongue",
  "Don't beat a dead horse",
  "A canary in a coal mine",
  "A bird in the hand",
  "The early bird catches worms",
  "The dog barked all night",
  "The fox ran through fields",
  "The horse kicked the gate",
  "The pig rolled in mud",
  "The rabbit hid in grass",
  "The sheep wandered the hills",
  "The duck swam across ponds",
  "The owl watched silently",
  "The frog leaped downstream",
  "The mouse stole the cheese",
  "The bear climbed the tree",
  "The wolf howled at midnight",
  "The deer crossed the path",
  "The goat ate the flowers",
  "The monkey climbed quickly",
  "The eagle soared above mountains",
  "The crow gathered shiny things",
  "The fish swam upstream",
  "The turtle moved slowly",
  "The snake slithered quietly",
  "The lion ruled the jungle",
  "The tiger stalked its prey",
  "The donkey carried supplies",
  "The camel crossed the desert",
  "The rooster greeted sunrise",
  "The peacock spread its feathers",
  "The bee buzzed loudly",
  "The butterfly landed softly",
  "The ant carried crumbs home",
  "The spider built a web",
  "The raccoon searched for food",
  "The squirrel buried acorns",
  "The whale surfaced slowly",
  "The dolphin jumped gracefully",
  "The seal rested on rocks",
  "The penguin slid on ice",
  "The otter floated downstream",
  "The parrot mimicked voices",
  "The flamingo stood on one leg",
  "The swan glided peacefully",
  "The pelican scooped fish",
  "The hawk circled overhead",
  "The geese flew southward",
  "The bison roamed freely",
  "The moose wandered forests",
  "The coyote disappeared quietly",
  "The jaguar moved silently",
  "The zebra crossed the plains",
  "The giraffe reached tall branches",
  "The hyena laughed strangely",
  "The buffalo stampeded suddenly",
  "The panther hid in shadows",
  "The lemur leaped tree branches",
  "The koala slept all afternoon",
  "The kangaroo bounced across fields",
  "The platypus swam underwater",
  "The porcupine raised its quills",
  "The hedgehog curled tightly",
  "The robin built a nest",
  "The sparrow chirped cheerfully",
  "The woodpecker tapped loudly",
  "The falcon dove swiftly",
  "The vulture circled patiently",
  "The ibis searched muddy banks",
  "The toucan balanced carefully",
  "The walrus rested heavily",
  "The lobster hid beneath rocks",
  "The crab walked sideways",
  "The octopus changed its color",
  "The jellyfish drifted slowly",
  "The starfish clung tightly",
  "The shrimp darted quickly",
  "The clam stayed buried",
  "The oyster formed pearls",
  "The snail crawled carefully",
  "The slug crossed the sidewalk",
  "The firefly glowed brightly",
  "The beetle crawled underground",
  "The cricket chirped at dusk",
  "The dragonfly skimmed water",
  "The moth flew toward light",
  "The bat hunted insects",
  "The alpaca grazed peacefully",
  "The llama carried heavy loads",
  "The ferret squeezed through gaps",
  "The weasel moved rapidly",
  "The badger dug tunnels",
  "The mole burrowed underground",
  "The reindeer crossed snowy hills",
  "The yak climbed steep paths",
  "The boar charged aggressively",
  "The chimp solved puzzles",
  "The orangutan swung slowly",
  "The sloth hung upside down",
  "The armadillo rolled defensively",
  "The possum played dead",
  "The skunk sprayed attackers"
]